config-version: 1.0

script-mode: true

chat-shooting:
  fireball-chance: 0.2

exp-bottle:
  min-count: 3
  max-count: 8

events:
  1000:
    action: BREAD
    target: player
  5000:
    action: BUFF
    target: random
  10000:
    action: DEBUFF
    target: all
